title: Hacker News Digest
description: Daily AI-generated summaries of top HN stories
url: "https://vu1n.github.io"
baseurl: "/zangosen-pages"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope: { path: "", type: "pages" }
    values: { layout: default }
